In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# import statsmodels.formula.api as smf
import statsmodels.api as sm
from statsmodels.stats.multitest import fdrcorrection
import os
import datetime
print(datetime.datetime.now().strftime('%Y-%m-%d'))

import sys
sys.path.append('/data100t1/home/wanying/lab_code/utils')
from volcano_plot import volcano_plot
from QQplot_v6 import qqplot

2024-07-08

In [7]:
fn_pheno = '/data100t1/share/CCHC/phenotypes/0724/cchc_phenotypes_0724.txt'
cols = ['RRID', 'LABID', 'ADA2010_Cat', 'TE_kPa', 'TE_CAP_Med', 'FAST_Score',
        'agile3','agile4', 'CREA', 'BUN', 'CKD_EPI_GFR_Calc', 'APRI', 'FIB4_U']
df_pheno = pd.read_csv(fn_pheno, sep='|', dtype=str)[cols]
df_pheno.head()

,RRID,LABID,ADA2010_Cat,TE_kPa,TE_CAP_Med,FAST_Score,agile3,agile4,CREA,BUN,CKD_EPI_GFR_Calc,APRI,FIB4_U
0,BD0001,BD4001,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BD0001,5Y0002,1.0,NaN,NaN,NaN,NaN,NaN,0.5,NaN,128.9956551967574,0.450112528132033,0.64687765648063
2,BD0002,BD4002,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BD0002,5Y0024,3.0,NaN,NaN,NaN,NaN,NaN,0.8,NaN,83.61934381934154,0.24481566820276499,0.9700574593253465
4,BD0002,10Y0098,3.0,NaN,NaN,NaN,NaN,NaN,0.7,16.0,94.26284477083404,0.25155371411660254,1.102448227716442

In [8]:
lip_path = '/data100t1/home/wanying/CCHC/lipidomics/20240529_differential_abundance_analysis/inputs/'
# lip_fn = 'lipid_class.with_covar_pcair_pc.log2.discovery.csv'
lip_fn = 'lipid_species.with_covar_pcair_pc.log2.discovery.csv'
df_lip = pd.read_csv(f'{lip_path}/{lip_fn}', sep='|', dtype=str)